version: 2
updates:
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
