on: push
name: Test and publish release
jobs:
  branchMaster:
    name: branch master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: mix deps.get
        uses: caycehouse/actions/elixir/1.9.0@master
        with:
          entrypoint: mix
          args: deps.get
      - name: "mix format.check"
        uses: "caycehouse/actions/elixir/1.9.0@master"
        with:
          entrypoint: mix
          args: format --check-formatted
      - name: yarn install
        uses: docker://node:lts-alpine
        with:
          entrypoint: yarn
          args: --cwd assets install
      - name: mix deps.compile (test)
        uses: caycehouse/actions/elixir/1.8.2-postgres@master
        env:
          MIX_ENV: test
        with:
          entrypoint: mix
          args: deps.compile
      - name: mix test
        uses: caycehouse/actions/elixir/1.8.2-postgres@master
        env:
          MIX_ENV: test
        with:
          args: test
      - name: yarn deploy
        uses: docker://node:lts-alpine
        with:
          entrypoint: yarn
          args: --cwd assets deploy
        if: github.ref == 'refs/heads/master'
      - name: mix deps.compile (prod)
        uses: caycehouse/actions/elixir/1.9.0@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        with:
          entrypoint: mix
          args: deps.compile
        if: github.ref == 'refs/heads/master'
      - name: mix phx.digest
        uses: caycehouse/actions/elixir/1.9.0@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MIX_ENV: prod
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        with:
          entrypoint: mix
          args: phx.digest
        if: github.ref == 'refs/heads/master'
      - name: mix release
        uses: caycehouse/actions/elixir/1.9.0@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MIX_ENV: prod
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        with:
          entrypoint: mix
          args: release
        if: github.ref == 'refs/heads/master'
      - name: github release
        uses: caycehouse/actions/bin/ghr@master
        env:
          APPLICATION: teamdynamix_tv
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PATH: _build/prod/rel
        if: github.ref == 'refs/heads/master'
